### ISSUE TITLE
make doesn't rebuild after running cmake with different arguments

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/aiot_sdk#65]
I built the internal memory version of bare-metal/cifar10
cmake ../
make

Then I want to build the external LPDDR memory version:
cmake ../ -DUSE_EXTMEM=1
make

I expect make to rebuild objects and link but it doesn't. This is the trace:
> make
[100%] Built target cifar10

**Comment by keithm-xmos** [comment]
Closing as this is a CMake issue, not SDK
